DazzlingFugu/ember-cli-embedded

.dependabot/config.yml
Create basic configuration file for @dependabot .
=> JS-261 - Dependabot : create configuration file

.dependabot/config.yml
---
Relates to https://github.com/peopledoc/tribe-js/pull/201.
=> JS-261 - Dependabot: only ignore updates of `ember-cli`

README.md
- Add CI badge in the README (#97)
- Add Ember Observer Score badge in the README (#97)
- Add License badge in the README (#97)
=> doc: add CI badge in the README

.github/workflows/ci.yml, config/ember-try.js
When editing the list of scenarios, I came across this error:
=> CI - Disable `ember-try` scenario `ember-canary`

.github/workflows/ci.yml, config/ember-try.js
=> CI - Remove useless testing scenarios

addon/initializers/embedded.ts
https://api.emberjs.com/ember/3.24/functions/@ember%2Fdebug/deprecate
=> fix: update import path of `deprecate`

.eslintrc.js, addon/initializers/embedded.ts, addon/services/embedded.ts, tests/unit/initializers/embedded-test.ts, tests/unit/instance-initializers/embedded-test.ts, tsconfig.json
Enforce a stronger TypeScript configuration by enabling all of the strict mode family options.
https://www.typescriptlang.org/tsconfig#strict :
> The `strict` flag enables a wide range of type checking behaviour that results in stronger guarantees of program correctness. Turning this on is equivalent to enabling all of the strict mode family options
From the add-on [`ember-cli-typescript`](https://ember-cli-typescript.com/docs/ts-guide/using-ts-effectively#incremental-adoption):
> Set "noEmitOnError": true in the "compilerOptions" hash in your `tsconfig.json` – it will help a lot if you can be sure that for the parts of your app you have added types to are still correct. And you'll get nice feedback immediately when you have type errors that way!
A good way to ensure nothing is emitted if …
=> Stricter TypeScript settings

package.json
=> Release v2

addon/initializers/embedded.ts, package.json, yarn.lock
Keys `for` and `since` were added to deprecate options in order to avoid a warning.
=> Fix/ new deprecated structure

.eslintignore, .eslintrc.js, .github/workflows/ci.yml, .github/workflows/tag-release-publish.yml, .template-lintrc.js, CONTRIBUTING.md, README.md, config/ember-try.js, ember-cli-build.js, package.json, tests/dummy/config/ember-cli-update.json, tests/dummy/config/targets.js, tests/index.html, yarn.lock
This version has been discontinued in August 2020 and is no longer maintained:
https://emberjs.com/releases/lts/
See https://github.com/atlassian/yarn-deduplicate.
=> CI - Reuse organisation's workflows to lint, test, tag and publish

package.json
See https://github.com/atlassian/yarn-deduplicate.
Make the workflow `tag-release-publish` waits for the workflow `CI` to finish, so that they run sequentially (the same way jobs' steps are run sequentially).
Surprisingly, while a new run of the workflow is triggered when pushing new changes, any previous workflow still running is not cancelled, resulting in a waste of resources.
We now use the `concurrency` setting to ensure that only a single workflow, using the same concurrency group, will run at a time.
- https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules
- https://github.com/lirantal/lockfile-lint
Previously the concurrency group's name was empty when running on `master` ([see the faulty …
=> build: release v2.4.0

addon/initializers/embedded.ts, tsconfig.json
Attempt to fix #186.
Fix successfully tested against a fresh Ember.js app in version `4.4.0`.
Tests suite successfully ran against Node.js v12, v14 and v16.
Temporarily disable `noEmitOnError` TS rule to unblock ember-try scenarios in the CI, to be turned on when we manage to fix type errors in this repo for ember-try scenarios.
=> fix: bind `application` to `start` function

package.json, yarn.lock
Launch `yarn-deduplicate` (#205)
Bumps [`ember-auto-import`](https://www.npmjs.com/package/ember-auto-import) from 2.2.3 to 2.4.2 (#205)
Bumps [`webpack`](https://www.npmjs.com/package/webpack) from 5.62.1 to 5.74.0 (#205)
=> Build/ update ember-auto-import & webpack, clean dependencies

.github/workflows/ci.yml, .github/workflows/tag-release-publish.yml, README.md, package.json, yarn.lock
=> breaking: drop node 12 support

.github/workflows/ci.yml, README.md, config/ember-try.js
These versions are not compatible with `ember-qunit` version.
For now, we have a bug with the `fs-extra` dependency of `ember-try`. We'll investigate after fixing the CI to unblock dependencies updates.
=> BREAKING Build/ Drop support for Ember 3.20 and 3.24

package.json
**BREAKING Build/ Drop support for Ember 3.20 and 3.24 #257**
**breaking: drop node 12 support #228**
- Bumps Ember from 4.4 to 4.8 using `ember-cli-update`
- Bumps a couple of dependencies: `@ember/test-helpers`, `@types/ember__test-helpers`, `ember-auto-import`, `ember-qunit`, `webpack`
Related to / closes #199 
- Move [`ember-export-application-global`](https://github.com/ember-cli/ember-export-application-global) in dependencies as it's no longer installed by the `app` blueprint.
- Add a ⚠️ about [`ember-export-application-global`](https://github.com/ember-cli/ember-export-application-global) in the README and fix a few typos > **Note**
To be up to date with [ember-cli-typescript](https://github.com/typed-ember/ember-cli-typescript) config and recommandations in `tsconfig.json` …
=> release: 3.0.0

README.md, addon/initializers/embedded.ts, addon/initializers/export-application-global.ts, app/initializers/export-application-global.js, package.json, tests/unit/initializers/export-application-global-test.ts, types/dummy/index.d.ts, types/index.ts, yarn.lock
- removes `ember-export-application-global` dependency
- creates `export-application-global` initializer
- adds `@ember/string` dependency (used by the above initializer) as it's no longer available in Ember 5 internally
- adds relevant tests
- updates documentation
`ember-cli/ember-export-application-global` has been [deprecated and archived](https://github.com/ember-cli/ember-export-application-global). But an exported application global is essential to an embedded SPA and therefore to ember-cli-embedded as well. So rather than adding a deprecated/archived module as a dependency to this addon, or to an app using this addon, this commit now hardcodes the `export-application-global` initializer into the ember-cli-embedded module itself, therefore removing the need for an external …
=> chore: hardcodes export-application-global

.github/workflows/tag-release-publish.yml
---
Twin PR with: https://github.com/DazzlingFugu/ember-feature-controls/pull/261
=> CI - Tag-release-publish - Use Node.js v18

package.json
Supersedes the previous release v4.0.0 (from #311).
To fix the auto-publish to npm, which previously failed:
https://github.com/DazzlingFugu/ember-cli-embedded/actions/runs/6855336980
=> Release v4.0.1

package.json, yarn.lock
This update should address the security warning CVE-2021-23337:
- https://github.com/DazzlingFugu/ember-cli-embedded/security/dependabot/63
- https://github.com/ember-cli/ember-cli/pull/10458
Because why not, while we are at it.
=> build: update `ember-cli` to v5.4.2

package.json
Changelog since our last version: https://github.com/DazzlingFugu/ember-cli-embedded/compare/v4.0.1...master
---
- Update `ember-cli` to v5.4.2 (#363)
- Update `ember-source` to v5.8.0 (#363)
- Run `yarn` to fix lockfile (#396)
- Bump `@typescript-eslint/parser` from 6.9.1 to 6.14.0 (#312)
- Bump `@babel/core` from 7.23.2 to 7.23.3 (#313)
- Bump `@types/ember__owner` from 4.0.7 to 4.0.8 (#314)
- Bump `@types/qunit` from 2.19.7 to 2.19.9 (#315)
- Bump `@types/ember__service` from 4.0.6 to 4.0.8 (#316)
- Bump `@types/ember__debug` from 4.0.6 to 4.0.7 (#317)
- Bump `@types/ember__engine` from 4.0.8 to 4.0.10 (#318)
- Bump `@ember/test-helpers` from 3.2.0 to 3.2.1 (#319)
- Bump `qunit-dom` from 2.0.0 to 3.0.0 (#320)
- Bump `@types/ember__component` from 4.0.19 to 4.0.21 (#322)
- Bump …
=> Release v4.1.0
